name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bing-translate-api:${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push gowinder/bing-translate-api:${{ github.ref_name }}
          docker tag gowinder/bing-translate-api:${{ github.ref_name }} gowinder/bing-translate-api:latest
          docker push gowinder/bing-translate-api:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/compose/bing-translate-proxy
            /home/ubuntu/.local/bin/docker-compose pull
            /home/ubuntu/.local/bin/docker-compose up -d